server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://naming-server:8761/eureka}
spring:
  application:
    name: exchange-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3321/exchange_service
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
springdoc:
  api-docs:
    path: exchange-service/v3/api-docs
  swagger-ui:
    url: exchange-service/v3/api-docs
  override-server-url: true


#-Dserver.port=8001 -> na config VM options do Startup 8001
# HeidiSQL - foo_bar -> exchange_service e book_service